### ISSUE TITLE
No module named 'covid'

### ISSUE THREAD

**Issue by fixerboy2009** [AstroBolo/H.A.L#1]
C:\Users\User\H.A.L>python main.py
Traceback (most recent call last):
  File "C:\Users\User\H.A.L\main.py", line 21, in <module>
    from covid import Covid #To get coivd data
ModuleNotFoundError: No module named 'covid'

**Comment by AstroBolo** [comment]
thank you for this means you have to install covid but the latest realize of has fixed this
